palavra=input('Digite algo:')
print('O tipo primitivo desse valor é:',type(palavra))
print('Só tem espaços?',palavra.isspace())
print('É numerico? ',palavra.isnumeric())
print('É alfabético? ',palavra.isalpha())
print('É alfanumérico? ',palavra.isalnum())
print('É maiúscula? ',palavra.isupper())
print('É minúscula? ',palavra.islower())
print('É capitalizada? ',palavra.istitle())